### ISSUE TITLE
Find a localised source of names

### ISSUE THREAD

**Issue by ghostflame** [kierun/pynpc#3]
### What is the problem?

1. We don't have a source of names
2. It needs to be localised, as generic names won't do
3. Probably need a fully localised source, then a mixer to bring in several sources to any suppported location
4. Eg London would have a mix of UK origin, various european origin and various global origin names

**Comment by kierun** [comment]
And that is not even consider fantasy / SciFi names…

I wonder if any of these random name generators have an API we could call?

- [Mithril land mages](https://www.mithrilandmages.com/utilities/Modern.php)
- [Donjon](https://donjon.bin.sh)
- [Fantasy name generator](https://www.fantasynamegenerators.com)
- … Others?

Clearly, we would need to ask permission to use their data/API.

**Comment by kierun** [comment]
Here are a few more. Thanks @stevecooperorg 

- [Muna](https://github.com/ironarachne/muna) has an API too.
- [API name fake](https://api.name-fake.com/nl_BE/female/)

**Comment by kierun** [comment]
[Completed](https://github.com/kierun/pynpc/pull/100)
